name: indexscroll_listview_builder
description: Enhanced ListView.builder with index-based programmatic scrolling, alignment control, offset handling, and optional customizable scrollbar for Flutter.
issue_tracker: https://github.com/SoundSliced/indexscroll_listview_builder/issues
repository: https://github.com/SoundSliced/indexscroll_listview_builder
version: 3.0.1
homepage: https://github.com/SoundSliced/indexscroll_listview_builder

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

